---
- name: add kernel table icvpn
  lineinfile: dest=/etc/iproute2/rt_tables regexp='^{{ icvpn_kernel_table }}' line='{{ icvpn_kernel_table }} icvpn'

- name: add wheezy backports for bird
  apt_repository: repo='deb http://http.debian.net/debian wheezy-backports main'
  when: ansible_distribution_release == "wheezy"

- name: install bird via debian-backports
  apt: name=bird state=present default_release=wheezy-backports update_cache=yes
  when: ansible_distribution_release == "wheezy"

- name: install bird
  apt: name=bird state=present update_cache=yes
  when: ansible_distribution_release == "jessie"

- name: esure /etc/bird/bird.d exists
  file: dest=/etc/bird/bird.d state=directory

- name: template /etc/bird/bird.conf
  template: src=bird.conf.j2 dest='/etc/bird/bird.conf' owner=root group=root mode='0644'
  notify:
  - reload bird config

- name: template /etc/bird/bird.d/01-icvpn.conf
  template: src=icvpn.conf.j2 dest='/etc/bird/bird.d/01-icvpn.conf' owner=root group=root mode='0644'
  notify:
  - reload bird config

- name: esure /etc/bird/bird6.d exists
  file: dest=/etc/bird/bird6.d state=directory

- name: template /etc/bird/bird6.conf
- template: src=bird6.conf.j2 dest='/etc/bird/bird6.conf' owner=root group=root mode='0644'
  notify:
  - reload bird6 config

- name: template /etc/bird/bird6.d/01-icvpn.conf
- template: src=icvpn6.conf.j2 dest='/etc/bird/bird6.d/01-icvpn6.conf' owner=root group=root mode='0644'
  notify:
  - reload bird6 config
