---
- name: Install packages
  action: apt pkg={{item}}
  with_items:
  - tinc
  - git-core

- name: Clone icvpn git
  git: repo=https://github.com/freifunk/icvpn.git dest=/etc/tinc/icvpn 

- lineinfile: dest=/etc/tinc/nets.boot line=icvpn

- name: template tinc conf
  template: src=tinc.conf.j2 dest=/etc/tinc/icvpn/tinc.conf mode='0644' owner=root group=root
  notify:
    - reload tinc

- name: template tinc-up
  template: src=tinc-up.j2 dest=/etc/tinc/icvpn/tinc-up mode='0744' owner=root group=root

- name: template tinc-down
  template: src=tinc-down.j2 dest=/etc/tinc/icvpn/tinc-down mode='0744' owner=root group=root

- name: Generate tinc keys
  command: /usr/sbin/tincd -n icvpn -K 4096
  args:
    creates: /etc/tinc/icvpn/rsa_key.priv
  notify:
    - reload tinc

- name: execute post-merge script
  command: /etc/tinc/icvpn/scripts/post-merge
  args:
    chdir: /etc/tinc/icvpn
  notify:
    - reload tinc

- service: name=tinc state=started

- name: clone icvpn-meta repo
  git: repo=https://github.com/freifunk/icvpn-meta.git dest=/var/lib/icvpn-meta

- name: clone icvpn-scripts repo  
  git: repo=https://github.com/freifunk/icvpn-scripts dest=/opt/icvpn-scripts

- name: copy icvpn-update
  copy: src=icvpn-update dest=/etc/cron.hourly/icvpn-update mode='0744' owner=root group=root

 
